name: Deploy Flask app to Cloudflare Workers

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install Wrangler CLI
      - name: Install Wrangler CLI
        run: |
          npm install -g wrangler

      # Step 5: Configure Cloudflare authentication
      - name: Set up Cloudflare API Token
        uses: cloudflare/wrangler-action@v1
        with:
          api_token: ${{ secrets.CF_API_TOKEN }}  # Set Cloudflare API Token in GitHub secrets

      # Step 6: Deploy to Cloudflare Workers
      - name: Deploy to Cloudflare Workers
        run: |
          wrangler publish
